/**
 * OrcaSlicer settings definitions for the settings panel.
 *
 * Types, default values, group definitions, and visibility logic.
 * Data sourced from default-project-settings.json (~850 keys).
 */

export type SettingType = 'number' | 'text' | 'select' | 'toggle' | 'textarea';

export interface SettingDef {
  key: string;
  label: string;
  type: SettingType;
  step?: string;
  options?: string[];
  optionLabels?: Record<string, string>;
  showWhen?: { key: string; value: string | string[] };
  notWhen?: { key: string; value: string | string[] };
}

export interface SettingGroup {
  id: string;
  label: string;
  defaultCollapsed: boolean;
  settings: SettingDef[];
}

// Default values extracted from default-project-settings.json (first element for arrays)
export const DEFAULT_VALUES: Record<string, string> = {
  layer_height: '0.2',
  initial_layer_height: '0.25',
  initial_layer_print_height: '0.2',
  wall_loops: '2',
  top_shell_layers: '4',
  bottom_shell_layers: '3',
  top_shell_thickness: '0.6',
  bottom_shell_thickness: '0',
  ensure_vertical_shell_thickness: 'ensure_all',
  alternate_extra_wall: '0',
  detect_overhang_wall: '1',
  optimize_wall_print_order: '0',
  only_one_wall_first_layer: '0',
  only_one_wall_top: '0',
  precise_outer_wall: '1',
  precise_z_height: '0',
  wall_generator: 'arachne',
  wall_sequence: 'inner wall/outer wall',
  line_width: '0',
  initial_layer_line_width: '0.5',
  outer_wall_line_width: '0.42',
  inner_wall_line_width: '0.45',
  internal_solid_infill_line_width: '0.42',
  sparse_infill_line_width: '0.45',
  top_surface_line_width: '0.42',
  support_line_width: '0.42',
  gap_infill_speed: '30',
  outer_wall_speed: '60',
  inner_wall_speed: '60',
  internal_solid_infill_speed: '100',
  sparse_infill_speed: '100',
  top_surface_speed: '100',
  initial_layer_speed: '30',
  initial_layer_infill_speed: '60',
  travel_speed: '120',
  bridge_speed: '25',
  support_speed: '80',
  support_interface_speed: '80',
  small_perimeter_speed: '50%',
  enable_arc_fitting: '0',
  default_acceleration: '500',
  outer_wall_acceleration: '500',
  inner_wall_acceleration: '10000',
  initial_layer_acceleration: '300',
  sparse_infill_acceleration: '100%',
  top_surface_acceleration: '500',
  travel_acceleration: '10000',
  bridge_acceleration: '50%',
  default_jerk: '0',
  outer_wall_jerk: '9',
  inner_wall_jerk: '9',
  top_surface_jerk: '9',
  travel_jerk: '12',
  initial_layer_jerk: '9',
  infill_jerk: '9',
  resonance_avoidance: '0',
  sparse_infill_density: '20%',
  sparse_infill_pattern: 'crosshatch',
  internal_solid_infill_pattern: 'monotonic',
  top_surface_pattern: 'monotonicline',
  bottom_surface_pattern: 'monotonic',
  solid_infill_direction: '45',
  infill_direction: '45',
  infill_combination: '0',
  fill_angle: '45',
  bridge_angle: '0',
  detect_narrow_internal_solid_infill: '1',
  minimum_sparse_infill_area: '15',
  infill_wall_overlap: '15%',
  enable_support: '0',
  support_type: 'normal(auto)',
  support_threshold_angle: '30',
  support_angle: '0',
  support_on_build_plate_only: '0',
  support_top_z_distance: '0.2',
  support_bottom_z_distance: '0.2',
  support_object_xy_distance: '0.35',
  support_interface_top_layers: '3',
  support_interface_bottom_layers: '0',
  support_interface_spacing: '0.5',
  support_interface_pattern: 'auto',
  support_filament: '0',
  support_interface_filament: '0',
  support_expansion: '0',
  support_style: 'default',
  independent_support_layer_height: '1',
  support_remove_small_overhang: '1',
  enforce_support_layers: '0',
  tree_support_branch_angle: '40',
  tree_support_branch_distance: '5',
  tree_support_branch_diameter: '5',
  tree_support_tip_diameter: '0.8',
  tree_support_branch_angle_organic: '40',
  tree_support_branch_distance_organic: '1',
  tree_support_branch_diameter_organic: '2',
  tree_support_wall_count: '0',
  tree_support_auto_brim: '1',
  tree_support_brim_width: '3',
  brim_type: 'auto_brim',
  brim_width: '0',
  brim_object_gap: '0',
  brim_ears_detection_length: '1',
  brim_ears_max_angle: '125',
  skirt_distance: '2',
  skirt_loops: '1',
  skirt_height: '1',
  skirt_speed: '50',
  draft_shield: 'disabled',
  single_loop_draft_shield: '0',
  nozzle_temperature: '200',
  nozzle_temperature_initial_layer: '200',
  hot_plate_temp: '45',
  hot_plate_temp_initial_layer: '45',
  cool_plate_temp: '35',
  cool_plate_temp_initial_layer: '35',
  textured_plate_temp: '45',
  textured_plate_temp_initial_layer: '45',
  chamber_temperature: '0',
  activate_chamber_temp_control: '0',
  curr_bed_type: 'Cool Plate',
  fan_min_speed: '20',
  fan_max_speed: '100',
  fan_cooling_layer_time: '60',
  overhang_fan_speed: '100',
  overhang_fan_threshold: '95%',
  additional_cooling_fan_speed: '0',
  slow_down_for_layer_cooling: '1',
  slow_down_layer_time: '5',
  slow_down_min_speed: '10',
  close_fan_the_first_x_layers: '1',
  full_fan_speed_layer: '0',
  reduce_fan_stop_start_freq: '0',
  enable_overhang_bridge_fan: '1',
  fan_speedup_overhangs: '1',
  dont_slow_down_outer_wall: '0',
  retraction_length: '0.8',
  retraction_speed: '30',
  deretraction_speed: '0',
  z_hop: '0.4',
  z_hop_types: 'Slope Lift',
  retraction_minimum_travel: '2',
  retract_when_changing_layer: '0',
  retract_lift_above: '0',
  retract_lift_below: '0',
  wipe: '0',
  wipe_distance: '1',
  enable_prime_tower: '0',
  prime_tower_width: '60',
  prime_tower_brim_width: '3',
  prime_volume: '45',
  purge_in_prime_tower: '1',
  single_extruder_multi_material: '1',
  single_extruder_multi_material_priming: '0',
  ooze_prevention: '0',
  flush_multiplier: '0.3',
  flush_into_infill: '0',
  flush_into_objects: '0',
  flush_into_support: '1',
  prime_tower_brim_chamfer: '1',
  prime_tower_brim_chamfer_max_width: '4',
  wipe_tower_bridging: '10',
  wipe_tower_cone_angle: '30',
  wipe_tower_extra_flow: '100%',
  wipe_tower_extra_rib_length: '0',
  wipe_tower_extra_spacing: '100%',
  wipe_tower_filament: '0',
  wipe_tower_fillet_wall: '1',
  wipe_tower_max_purge_speed: '90',
  wipe_tower_no_sparse_layers: '0',
  wipe_tower_rib_width: '8',
  wipe_tower_wall_type: 'rectangle',
  enable_filament_ramming: '1',
  filament_minimal_purge_on_wipe_tower: '15',
  filament_loading_speed: '28',
  filament_loading_speed_start: '3',
  filament_unloading_speed: '90',
  filament_unloading_speed_start: '100',
  filament_cooling_moves: '4',
  filament_cooling_initial_speed: '2.2',
  filament_cooling_final_speed: '3.4',
  filament_toolchange_delay: '0',
  mmu_segmented_region_max_width: '0',
  mmu_segmented_region_interlocking_depth: '0',
  wipe_tower_rotation_angle: '0',
  elefant_foot_compensation: '0',
  elefant_foot_compensation_layers: '1',
  exclude_object: '0',
  spiral_mode: '0',
  gcode_add_line_number: '0',
  scan_first_layer: '0',
  pressure_advance: '0.02',
  adaptive_pressure_advance: '0',
  print_sequence: 'by layer',
  print_order: 'default',
  nozzle_type: 'undefine',
  xy_contour_compensation: '0',
  xy_hole_compensation: '0',
  z_offset: '0',
  resolution: '0.01',
  make_overhang_printable: '0',
  make_overhang_printable_angle: '55',
  fuzzy_skin: 'none',
  fuzzy_skin_thickness: '0.2',
  fuzzy_skin_point_distance: '0.3',
  seam_position: 'aligned',
  ironing_type: 'no ironing',
  ironing_speed: '20',
  ironing_flow: '10%',
  ironing_spacing: '0.1',
  filename_format: '{input_filename_base}_{filament_type[initial_tool]}_{print_time}.gcode',
  before_layer_change_gcode: '',
  layer_change_gcode: '',
  machine_start_gcode: 'G28 ; home all axes\nG1 Z5 F5000 ; lift nozzle\n',
  machine_end_gcode: 'M104 S0 ; turn off temperature\nG28 X0  ; home X axis\nM84     ; disable motors\n',
  change_filament_gcode: '',
  printing_by_object_gcode: '',
  gcode_comments: '0',
  disable_m73: '0',
};

export function isSettingVisible(def: SettingDef, settings: Record<string, string>): boolean {
  if (def.showWhen) {
    const current = settings[def.showWhen.key] ?? DEFAULT_VALUES[def.showWhen.key] ?? '';
    const values = Array.isArray(def.showWhen.value) ? def.showWhen.value : [def.showWhen.value];
    if (!values.includes(current)) return false;
  }
  if (def.notWhen) {
    const current = settings[def.notWhen.key] ?? DEFAULT_VALUES[def.notWhen.key] ?? '';
    const values = Array.isArray(def.notWhen.value) ? def.notWhen.value : [def.notWhen.value];
    if (values.includes(current)) return false;
  }
  return true;
}

// Helper: check if value contains substring (for tree/hybrid support types)
function containsAny(val: string, substrings: string[]): boolean {
  return substrings.some(s => val.includes(s));
}

export const SETTING_GROUPS: SettingGroup[] = [
  {
    id: 'quality',
    label: 'Quality',
    defaultCollapsed: false,
    settings: [
      { key: 'layer_height', label: 'Layer Height (mm)', type: 'number', step: '0.05' },
      { key: 'initial_layer_height', label: 'First Layer Height (mm)', type: 'number', step: '0.05' },
      { key: 'initial_layer_print_height', label: 'First Layer Print Height (mm)', type: 'number', step: '0.05' },
      { key: 'wall_loops', label: 'Wall Loops', type: 'number', step: '1' },
      { key: 'top_shell_layers', label: 'Top Solid Layers', type: 'number', step: '1' },
      { key: 'bottom_shell_layers', label: 'Bottom Solid Layers', type: 'number', step: '1' },
      { key: 'top_shell_thickness', label: 'Top Solid Thickness (mm)', type: 'number', step: '0.2' },
      { key: 'bottom_shell_thickness', label: 'Bottom Solid Thickness (mm)', type: 'number', step: '0.2' },
      { key: 'ensure_vertical_shell_thickness', label: 'Vertical Shell Thickness', type: 'select', options: ['ensure_all', 'ensure_moderate', 'none'] },
      { key: 'alternate_extra_wall', label: 'Alternate Extra Wall', type: 'toggle' },
      { key: 'detect_overhang_wall', label: 'Detect Overhang Wall', type: 'toggle' },
      { key: 'optimize_wall_print_order', label: 'Optimize Wall Print Order', type: 'toggle' },
      { key: 'only_one_wall_first_layer', label: 'Only One Wall First Layer', type: 'toggle' },
      { key: 'only_one_wall_top', label: 'Only One Wall Top', type: 'toggle' },
      { key: 'precise_outer_wall', label: 'Precise Outer Wall', type: 'toggle' },
      { key: 'precise_z_height', label: 'Precise Z Height', type: 'toggle' },
      { key: 'wall_generator', label: 'Wall Generator', type: 'select', options: ['arachne', 'classic'] },
      { key: 'wall_sequence', label: 'Wall Sequence', type: 'select', options: ['inner wall/outer wall', 'outer wall/inner wall', 'inner-outer-inner wall'] },
    ],
  },
  {
    id: 'line_width',
    label: 'Line Width',
    defaultCollapsed: true,
    settings: [
      { key: 'line_width', label: 'Default (mm)', type: 'number', step: '0.01' },
      { key: 'initial_layer_line_width', label: 'First Layer (mm)', type: 'number', step: '0.01' },
      { key: 'outer_wall_line_width', label: 'Outer Wall (mm)', type: 'number', step: '0.01' },
      { key: 'inner_wall_line_width', label: 'Inner Wall (mm)', type: 'number', step: '0.01' },
      { key: 'internal_solid_infill_line_width', label: 'Internal Solid (mm)', type: 'number', step: '0.01' },
      { key: 'sparse_infill_line_width', label: 'Sparse Infill (mm)', type: 'number', step: '0.01' },
      { key: 'top_surface_line_width', label: 'Top Surface (mm)', type: 'number', step: '0.01' },
      { key: 'support_line_width', label: 'Support (mm)', type: 'number', step: '0.01' },
      { key: 'gap_infill_speed', label: 'Gap Infill Speed (mm/s)', type: 'number', step: '5' },
    ],
  },
  {
    id: 'speed',
    label: 'Speed',
    defaultCollapsed: true,
    settings: [
      { key: 'outer_wall_speed', label: 'Outer Wall (mm/s)', type: 'number', step: '5' },
      { key: 'inner_wall_speed', label: 'Inner Wall (mm/s)', type: 'number', step: '5' },
      { key: 'internal_solid_infill_speed', label: 'Internal Solid (mm/s)', type: 'number', step: '5' },
      { key: 'sparse_infill_speed', label: 'Sparse Infill (mm/s)', type: 'number', step: '5' },
      { key: 'top_surface_speed', label: 'Top Surface (mm/s)', type: 'number', step: '5' },
      { key: 'initial_layer_speed', label: 'First Layer (mm/s)', type: 'number', step: '5' },
      { key: 'initial_layer_infill_speed', label: 'First Layer Infill (mm/s)', type: 'number', step: '5' },
      { key: 'travel_speed', label: 'Travel (mm/s)', type: 'number', step: '10' },
      { key: 'bridge_speed', label: 'Bridge (mm/s)', type: 'number', step: '5' },
      { key: 'support_speed', label: 'Support (mm/s)', type: 'number', step: '5' },
      { key: 'support_interface_speed', label: 'Support Interface (mm/s)', type: 'number', step: '5' },
      { key: 'small_perimeter_speed', label: 'Small Perimeter (%)', type: 'text' },
      { key: 'enable_arc_fitting', label: 'Arc Fitting', type: 'toggle' },
      { key: 'default_acceleration', label: 'Default Accel (mm/s\u00B2)', type: 'number', step: '50' },
      { key: 'outer_wall_acceleration', label: 'Outer Wall Accel', type: 'number', step: '50' },
      { key: 'inner_wall_acceleration', label: 'Inner Wall Accel', type: 'number', step: '50' },
      { key: 'initial_layer_acceleration', label: 'First Layer Accel', type: 'number', step: '50' },
      { key: 'sparse_infill_acceleration', label: 'Infill Accel', type: 'text' },
      { key: 'top_surface_acceleration', label: 'Top Surface Accel', type: 'number', step: '50' },
      { key: 'travel_acceleration', label: 'Travel Accel', type: 'number', step: '100' },
      { key: 'bridge_acceleration', label: 'Bridge Accel', type: 'text' },
      { key: 'default_jerk', label: 'Default Jerk (mm/s)', type: 'number', step: '1' },
      { key: 'outer_wall_jerk', label: 'Outer Wall Jerk', type: 'number', step: '1' },
      { key: 'inner_wall_jerk', label: 'Inner Wall Jerk', type: 'number', step: '1' },
      { key: 'top_surface_jerk', label: 'Top Surface Jerk', type: 'number', step: '1' },
      { key: 'travel_jerk', label: 'Travel Jerk', type: 'number', step: '1' },
      { key: 'initial_layer_jerk', label: 'First Layer Jerk', type: 'number', step: '1' },
      { key: 'infill_jerk', label: 'Infill Jerk', type: 'number', step: '1' },
      { key: 'resonance_avoidance', label: 'Resonance Avoidance', type: 'toggle' },
    ],
  },
  {
    id: 'infill',
    label: 'Infill',
    defaultCollapsed: true,
    settings: [
      { key: 'sparse_infill_density', label: 'Density (%)', type: 'text' },
      { key: 'sparse_infill_pattern', label: 'Pattern', type: 'select', options: ['crosshatch', 'gyroid', 'grid', 'honeycomb', 'lines', 'rectilinear', 'tri-hexagon', 'cubic', 'adaptive_cubic', '3dhoneycomb'] },
      { key: 'internal_solid_infill_pattern', label: 'Solid Pattern', type: 'select', options: ['monotonic', 'monotonicline', 'rectilinear', 'concentric'] },
      { key: 'top_surface_pattern', label: 'Top Surface Pattern', type: 'select', options: ['monotonicline', 'monotonic', 'rectilinear', 'concentric'] },
      { key: 'bottom_surface_pattern', label: 'Bottom Surface Pattern', type: 'select', options: ['monotonic', 'monotonicline', 'rectilinear', 'concentric'] },
      { key: 'solid_infill_direction', label: 'Solid Direction (\u00B0)', type: 'number', step: '15' },
      { key: 'infill_direction', label: 'Infill Direction (\u00B0)', type: 'number', step: '15' },
      { key: 'infill_combination', label: 'Infill Combination', type: 'toggle' },
      { key: 'fill_angle', label: 'Fill Angle (\u00B0)', type: 'number', step: '15' },
      { key: 'bridge_angle', label: 'Bridge Angle (\u00B0)', type: 'number', step: '15' },
      { key: 'detect_narrow_internal_solid_infill', label: 'Detect Narrow Solid Infill', type: 'toggle' },
      { key: 'minimum_sparse_infill_area', label: 'Min Infill Area (mm\u00B2)', type: 'number', step: '5' },
      { key: 'infill_wall_overlap', label: 'Infill Wall Overlap', type: 'text' },
    ],
  },
  {
    id: 'support',
    label: 'Support',
    defaultCollapsed: true,
    settings: [
      { key: 'enable_support', label: 'Enable Support', type: 'toggle' },
      { key: 'support_type', label: 'Support Type', type: 'select', options: ['normal(auto)', 'normal(manual)', 'tree(auto)', 'tree(manual)', 'hybrid(auto)', 'hybrid(manual)'], showWhen: { key: 'enable_support', value: '1' } },
      { key: 'support_threshold_angle', label: 'Threshold Angle (\u00B0)', type: 'number', step: '5', showWhen: { key: 'enable_support', value: '1' } },
      { key: 'support_angle', label: 'Support Angle (\u00B0)', type: 'number', step: '5', showWhen: { key: 'enable_support', value: '1' } },
      { key: 'support_on_build_plate_only', label: 'On Build Plate Only', type: 'toggle', showWhen: { key: 'enable_support', value: '1' } },
      { key: 'support_top_z_distance', label: 'Top Z Distance (mm)', type: 'number', step: '0.1', showWhen: { key: 'enable_support', value: '1' } },
      { key: 'support_bottom_z_distance', label: 'Bottom Z Distance (mm)', type: 'number', step: '0.1', showWhen: { key: 'enable_support', value: '1' } },
      { key: 'support_object_xy_distance', label: 'Object XY Distance (mm)', type: 'number', step: '0.1', showWhen: { key: 'enable_support', value: '1' } },
      { key: 'support_interface_top_layers', label: 'Interface Top Layers', type: 'number', step: '1', showWhen: { key: 'enable_support', value: '1' } },
      { key: 'support_interface_bottom_layers', label: 'Interface Bottom Layers', type: 'number', step: '1', showWhen: { key: 'enable_support', value: '1' } },
      { key: 'support_interface_spacing', label: 'Interface Spacing (mm)', type: 'number', step: '0.1', showWhen: { key: 'enable_support', value: '1' } },
      { key: 'support_interface_pattern', label: 'Interface Pattern', type: 'select', options: ['auto', 'rectilinear', 'rectilinear_interlaced', 'concentric', 'honeycomb'], showWhen: { key: 'enable_support', value: '1' } },
      { key: 'support_filament', label: 'Support Filament', type: 'select', options: ['0', '1'], showWhen: { key: 'enable_support', value: '1' } },
      { key: 'support_interface_filament', label: 'Interface Filament', type: 'select', options: ['0', '1'], showWhen: { key: 'enable_support', value: '1' } },
      { key: 'support_expansion', label: 'Support Expansion (mm)', type: 'number', step: '0.5', showWhen: { key: 'enable_support', value: '1' } },
      { key: 'support_style', label: 'Support Style', type: 'select', options: ['default', 'grid', 'snug'], showWhen: { key: 'enable_support', value: '1' } },
      { key: 'independent_support_layer_height', label: 'Independent Layer Height', type: 'toggle', showWhen: { key: 'enable_support', value: '1' } },
      { key: 'support_remove_small_overhang', label: 'Remove Small Overhang', type: 'toggle', showWhen: { key: 'enable_support', value: '1' } },
      { key: 'enforce_support_layers', label: 'Enforce Support Layers', type: 'number', step: '1', showWhen: { key: 'enable_support', value: '1' } },
      // Tree support sub-settings
      { key: 'tree_support_branch_angle', label: 'Tree Branch Angle (\u00B0)', type: 'number', step: '1', showWhen: { key: 'support_type', value: ['tree(auto)', 'tree(manual)'] } },
      { key: 'tree_support_branch_distance', label: 'Tree Branch Distance (mm)', type: 'number', step: '1', showWhen: { key: 'support_type', value: ['tree(auto)', 'tree(manual)'] } },
      { key: 'tree_support_branch_diameter', label: 'Tree Branch Diameter (mm)', type: 'number', step: '0.5', showWhen: { key: 'support_type', value: ['tree(auto)', 'tree(manual)'] } },
      { key: 'tree_support_tip_diameter', label: 'Tree Tip Diameter (mm)', type: 'number', step: '0.1', showWhen: { key: 'support_type', value: ['tree(auto)', 'tree(manual)'] } },
      { key: 'tree_support_branch_angle_organic', label: 'Organic Branch Angle (\u00B0)', type: 'number', step: '1', showWhen: { key: 'support_type', value: ['tree(auto)', 'tree(manual)', 'hybrid(auto)', 'hybrid(manual)'] } },
      { key: 'tree_support_branch_distance_organic', label: 'Organic Branch Distance (mm)', type: 'number', step: '1', showWhen: { key: 'support_type', value: ['tree(auto)', 'tree(manual)', 'hybrid(auto)', 'hybrid(manual)'] } },
      { key: 'tree_support_branch_diameter_organic', label: 'Organic Branch Diameter (mm)', type: 'number', step: '0.5', showWhen: { key: 'support_type', value: ['tree(auto)', 'tree(manual)', 'hybrid(auto)', 'hybrid(manual)'] } },
      { key: 'tree_support_wall_count', label: 'Tree Wall Count', type: 'number', step: '1', showWhen: { key: 'support_type', value: ['tree(auto)', 'tree(manual)', 'hybrid(auto)', 'hybrid(manual)'] } },
      { key: 'tree_support_auto_brim', label: 'Tree Auto Brim', type: 'toggle', showWhen: { key: 'support_type', value: ['tree(auto)', 'tree(manual)', 'hybrid(auto)', 'hybrid(manual)'] } },
      { key: 'tree_support_brim_width', label: 'Tree Brim Width (mm)', type: 'number', step: '1', showWhen: { key: 'support_type', value: ['tree(auto)', 'tree(manual)', 'hybrid(auto)', 'hybrid(manual)'] } },
    ],
  },
  {
    id: 'brim',
    label: 'Brim & Skirt',
    defaultCollapsed: true,
    settings: [
      { key: 'brim_type', label: 'Brim Type', type: 'select', options: ['auto_brim', 'brim_ears', 'outer', 'inner', 'outer_and_inner', 'no_brim'] },
      { key: 'brim_width', label: 'Brim Width (mm)', type: 'number', step: '1' },
      { key: 'brim_object_gap', label: 'Brim Object Gap (mm)', type: 'number', step: '0.1' },
      { key: 'brim_ears_detection_length', label: 'Ear Detection Length (mm)', type: 'number', step: '0.5', showWhen: { key: 'brim_type', value: 'brim_ears' } },
      { key: 'brim_ears_max_angle', label: 'Ear Max Angle (\u00B0)', type: 'number', step: '5', showWhen: { key: 'brim_type', value: 'brim_ears' } },
      { key: 'skirt_distance', label: 'Skirt Distance (mm)', type: 'number', step: '1' },
      { key: 'skirt_loops', label: 'Skirt Loops', type: 'number', step: '1' },
      { key: 'skirt_height', label: 'Skirt Height (layers)', type: 'number', step: '1' },
      { key: 'skirt_speed', label: 'Skirt Speed (mm/s)', type: 'number', step: '5' },
      { key: 'draft_shield', label: 'Draft Shield', type: 'select', options: ['disabled', 'enabled', 'limited'] },
      { key: 'single_loop_draft_shield', label: 'Single Loop Draft Shield', type: 'toggle' },
    ],
  },
  {
    id: 'temperature',
    label: 'Temperature',
    defaultCollapsed: true,
    settings: [
      { key: 'nozzle_temperature', label: 'Nozzle (\u00B0C)', type: 'number', step: '5' },
      { key: 'nozzle_temperature_initial_layer', label: 'First Layer Nozzle (\u00B0C)', type: 'number', step: '5' },
      { key: 'curr_bed_type', label: 'Bed Type', type: 'select', options: ['Cool Plate', 'Hot Plate', 'Textured Plate', 'Textured Cool Plate', 'Supertack Plate'] },
      { key: 'hot_plate_temp', label: 'Hot Plate (\u00B0C)', type: 'number', step: '5' },
      { key: 'hot_plate_temp_initial_layer', label: 'First Layer Hot Plate (\u00B0C)', type: 'number', step: '5' },
      { key: 'cool_plate_temp', label: 'Cool Plate (\u00B0C)', type: 'number', step: '5' },
      { key: 'cool_plate_temp_initial_layer', label: 'First Layer Cool Plate (\u00B0C)', type: 'number', step: '5' },
      { key: 'textured_plate_temp', label: 'Textured Plate (\u00B0C)', type: 'number', step: '5' },
      { key: 'textured_plate_temp_initial_layer', label: 'First Layer Textured (\u00B0C)', type: 'number', step: '5' },
      { key: 'chamber_temperature', label: 'Chamber (\u00B0C)', type: 'number', step: '5' },
      { key: 'activate_chamber_temp_control', label: 'Chamber Temp Control', type: 'toggle' },
    ],
  },
  {
    id: 'cooling',
    label: 'Cooling',
    defaultCollapsed: true,
    settings: [
      { key: 'fan_min_speed', label: 'Min Fan Speed (%)', type: 'number', step: '5' },
      { key: 'fan_max_speed', label: 'Max Fan Speed (%)', type: 'number', step: '5' },
      { key: 'fan_cooling_layer_time', label: 'Fan Cooling Layer Time (s)', type: 'number', step: '5' },
      { key: 'overhang_fan_speed', label: 'Overhang Fan Speed (%)', type: 'number', step: '5' },
      { key: 'overhang_fan_threshold', label: 'Overhang Fan Threshold', type: 'text' },
      { key: 'additional_cooling_fan_speed', label: 'Additional Fan Speed (%)', type: 'number', step: '5' },
      { key: 'slow_down_for_layer_cooling', label: 'Slow Down for Cooling', type: 'toggle' },
      { key: 'slow_down_layer_time', label: 'Slow Down Layer Time (s)', type: 'number', step: '1' },
      { key: 'slow_down_min_speed', label: 'Slow Down Min Speed (mm/s)', type: 'number', step: '5' },
      { key: 'close_fan_the_first_x_layers', label: 'Close Fan First X Layers', type: 'number', step: '1' },
      { key: 'full_fan_speed_layer', label: 'Full Fan Speed Layer', type: 'number', step: '1' },
      { key: 'reduce_fan_stop_start_freq', label: 'Reduce Fan Stop/Start', type: 'toggle' },
      { key: 'enable_overhang_bridge_fan', label: 'Overhang Bridge Fan', type: 'toggle' },
      { key: 'fan_speedup_overhangs', label: 'Fan Speedup Overhangs', type: 'toggle' },
      { key: 'dont_slow_down_outer_wall', label: "Don't Slow Outer Wall", type: 'toggle' },
    ],
  },
  {
    id: 'retraction',
    label: 'Retraction',
    defaultCollapsed: true,
    settings: [
      { key: 'retraction_length', label: 'Length (mm)', type: 'number', step: '0.1' },
      { key: 'retraction_speed', label: 'Speed (mm/s)', type: 'number', step: '5' },
      { key: 'deretraction_speed', label: 'Deretraction Speed (mm/s)', type: 'number', step: '5' },
      { key: 'z_hop', label: 'Z Hop (mm)', type: 'number', step: '0.1' },
      { key: 'z_hop_types', label: 'Z Hop Type', type: 'select', options: ['Normal Lift', 'Slope Lift', 'Spiral Lift'] },
      { key: 'retraction_minimum_travel', label: 'Min Travel (mm)', type: 'number', step: '0.5' },
      { key: 'retract_when_changing_layer', label: 'Retract on Layer Change', type: 'toggle' },
      { key: 'retract_lift_above', label: 'Lift Above (mm)', type: 'number', step: '0.1' },
      { key: 'retract_lift_below', label: 'Lift Below (mm)', type: 'number', step: '0.1' },
      { key: 'wipe', label: 'Wipe', type: 'toggle' },
      { key: 'wipe_distance', label: 'Wipe Distance (mm)', type: 'number', step: '0.5', showWhen: { key: 'wipe', value: '1' } },
    ],
  },
  {
    id: 'multi_material',
    label: 'Multi Material',
    defaultCollapsed: true,
    settings: [
      // General
      { key: 'single_extruder_multi_material', label: 'Single Extruder Multi-Material', type: 'toggle' },
      { key: 'single_extruder_multi_material_priming', label: 'MMU Priming', type: 'toggle' },
      { key: 'ooze_prevention', label: 'Ooze Prevention', type: 'toggle' },
      // Prime Tower
      { key: 'enable_prime_tower', label: 'Enable Prime Tower', type: 'toggle' },
      { key: 'prime_tower_width', label: 'Tower Width (mm)', type: 'number', step: '1', showWhen: { key: 'enable_prime_tower', value: '1' } },
      { key: 'prime_tower_brim_width', label: 'Tower Brim Width (mm)', type: 'number', step: '1', showWhen: { key: 'enable_prime_tower', value: '1' } },
      { key: 'prime_tower_brim_chamfer', label: 'Tower Brim Chamfer', type: 'toggle', showWhen: { key: 'enable_prime_tower', value: '1' } },
      { key: 'prime_tower_brim_chamfer_max_width', label: 'Chamfer Max Width (mm)', type: 'number', step: '0.5', showWhen: { key: 'enable_prime_tower', value: '1' } },
      { key: 'prime_volume', label: 'Prime Volume (mm\u00B3)', type: 'number', step: '5', showWhen: { key: 'enable_prime_tower', value: '1' } },
      { key: 'purge_in_prime_tower', label: 'Purge in Tower', type: 'toggle', showWhen: { key: 'enable_prime_tower', value: '1' } },
      // Wipe Tower
      { key: 'wipe_tower_rotation_angle', label: 'Tower Rotation (\u00B0)', type: 'number', step: '15', showWhen: { key: 'enable_prime_tower', value: '1' } },
      { key: 'wipe_tower_bridging', label: 'Wipe Tower Bridging (mm)', type: 'number', step: '1', showWhen: { key: 'enable_prime_tower', value: '1' } },
      { key: 'wipe_tower_cone_angle', label: 'Cone Angle (\u00B0)', type: 'number', step: '5', showWhen: { key: 'enable_prime_tower', value: '1' } },
      { key: 'wipe_tower_extra_flow', label: 'Extra Flow', type: 'text', showWhen: { key: 'enable_prime_tower', value: '1' } },
      { key: 'wipe_tower_extra_rib_length', label: 'Extra Rib Length (mm)', type: 'number', step: '1', showWhen: { key: 'enable_prime_tower', value: '1' } },
      { key: 'wipe_tower_extra_spacing', label: 'Extra Spacing', type: 'text', showWhen: { key: 'enable_prime_tower', value: '1' } },
      { key: 'wipe_tower_filament', label: 'Tower Filament', type: 'select', options: ['0', '1'], showWhen: { key: 'enable_prime_tower', value: '1' } },
      { key: 'wipe_tower_fillet_wall', label: 'Fillet Wall', type: 'toggle', showWhen: { key: 'enable_prime_tower', value: '1' } },
      { key: 'wipe_tower_max_purge_speed', label: 'Max Purge Speed (mm/s)', type: 'number', step: '5', showWhen: { key: 'enable_prime_tower', value: '1' } },
      { key: 'wipe_tower_no_sparse_layers', label: 'No Sparse Layers', type: 'toggle', showWhen: { key: 'enable_prime_tower', value: '1' } },
      { key: 'wipe_tower_rib_width', label: 'Rib Width (mm)', type: 'number', step: '1', showWhen: { key: 'enable_prime_tower', value: '1' } },
      { key: 'wipe_tower_wall_type', label: 'Wall Type', type: 'select', options: ['rectangle', 'wave', 'rib'], showWhen: { key: 'enable_prime_tower', value: '1' } },
      // Flush
      { key: 'flush_multiplier', label: 'Flush Multiplier', type: 'text' },
      { key: 'flush_into_infill', label: 'Flush into Infill', type: 'toggle' },
      { key: 'flush_into_objects', label: 'Flush into Objects', type: 'toggle' },
      { key: 'flush_into_support', label: 'Flush into Support', type: 'toggle' },
      // Filament change
      { key: 'enable_filament_ramming', label: 'Filament Ramming', type: 'toggle' },
      { key: 'filament_minimal_purge_on_wipe_tower', label: 'Min Purge on Tower (mm\u00B3)', type: 'number', step: '1' },
      { key: 'filament_loading_speed', label: 'Loading Speed (mm/s)', type: 'number', step: '5' },
      { key: 'filament_loading_speed_start', label: 'Loading Start Speed (mm/s)', type: 'number', step: '5' },
      { key: 'filament_unloading_speed', label: 'Unloading Speed (mm/s)', type: 'number', step: '5' },
      { key: 'filament_unloading_speed_start', label: 'Unloading Start Speed (mm/s)', type: 'number', step: '5' },
      { key: 'filament_cooling_moves', label: 'Cooling Moves', type: 'number', step: '1' },
      { key: 'filament_cooling_initial_speed', label: 'Cooling Initial Speed (mm/s)', type: 'number', step: '0.5' },
      { key: 'filament_cooling_final_speed', label: 'Cooling Final Speed (mm/s)', type: 'number', step: '0.5' },
      { key: 'filament_toolchange_delay', label: 'Toolchange Delay (s)', type: 'number', step: '1' },
      // MMU segmentation
      { key: 'mmu_segmented_region_max_width', label: 'Segmented Region Max Width (mm)', type: 'number', step: '0.5' },
      { key: 'mmu_segmented_region_interlocking_depth', label: 'Interlocking Depth', type: 'number', step: '1' },
    ],
  },
  {
    id: 'advanced',
    label: 'Advanced',
    defaultCollapsed: true,
    settings: [
      { key: 'elefant_foot_compensation', label: 'Elephant Foot Comp (mm)', type: 'number', step: '0.05' },
      { key: 'elefant_foot_compensation_layers', label: 'Elephant Foot Layers', type: 'number', step: '1' },
      { key: 'exclude_object', label: 'Label Objects', type: 'toggle' },
      { key: 'spiral_mode', label: 'Spiral/Vase Mode', type: 'toggle' },
      { key: 'gcode_add_line_number', label: 'Gcode Line Numbers', type: 'toggle' },
      { key: 'scan_first_layer', label: 'Scan First Layer', type: 'toggle' },
      { key: 'pressure_advance', label: 'Pressure Advance', type: 'number', step: '0.01' },
      { key: 'adaptive_pressure_advance', label: 'Adaptive PA', type: 'toggle' },
      { key: 'print_sequence', label: 'Print Sequence', type: 'select', options: ['by layer', 'by object'] },
      { key: 'print_order', label: 'Print Order', type: 'select', options: ['default'] },
      { key: 'nozzle_type', label: 'Nozzle Type', type: 'select', options: ['undefine', 'hardened_steel', 'stainless_steel', 'brass', 'ruby'] },
      { key: 'xy_contour_compensation', label: 'XY Contour Comp (mm)', type: 'number', step: '0.01' },
      { key: 'xy_hole_compensation', label: 'XY Hole Comp (mm)', type: 'number', step: '0.01' },
      { key: 'z_offset', label: 'Z Offset (mm)', type: 'number', step: '0.01' },
      { key: 'resolution', label: 'Resolution (mm)', type: 'number', step: '0.01' },
      { key: 'make_overhang_printable', label: 'Make Overhang Printable', type: 'toggle' },
      { key: 'make_overhang_printable_angle', label: 'Overhang Angle (\u00B0)', type: 'number', step: '5', showWhen: { key: 'make_overhang_printable', value: '1' } },
      { key: 'fuzzy_skin', label: 'Fuzzy Skin', type: 'select', options: ['none', 'external', 'all', 'all_no_overhangs'] },
      { key: 'fuzzy_skin_thickness', label: 'Fuzzy Thickness (mm)', type: 'number', step: '0.1', notWhen: { key: 'fuzzy_skin', value: 'none' } },
      { key: 'fuzzy_skin_point_distance', label: 'Fuzzy Point Distance (mm)', type: 'number', step: '0.1', notWhen: { key: 'fuzzy_skin', value: 'none' } },
      { key: 'seam_position', label: 'Seam Position', type: 'select', options: ['aligned', 'rear', 'left', 'right', 'nearest', 'staggered'] },
      { key: 'ironing_type', label: 'Ironing', type: 'select', options: ['no ironing', 'top surfaces', 'topmost only', 'all solid'] },
      { key: 'ironing_speed', label: 'Ironing Speed (mm/s)', type: 'number', step: '5', notWhen: { key: 'ironing_type', value: 'no ironing' } },
      { key: 'ironing_flow', label: 'Ironing Flow', type: 'text', notWhen: { key: 'ironing_type', value: 'no ironing' } },
      { key: 'ironing_spacing', label: 'Ironing Spacing (mm)', type: 'number', step: '0.05', notWhen: { key: 'ironing_type', value: 'no ironing' } },
    ],
  },
  {
    id: 'gcode',
    label: 'G-code',
    defaultCollapsed: true,
    settings: [
      { key: 'filename_format', label: 'Filename Format', type: 'text' },
      { key: 'machine_start_gcode', label: 'Start Gcode', type: 'textarea' },
      { key: 'machine_end_gcode', label: 'End Gcode', type: 'textarea' },
      { key: 'before_layer_change_gcode', label: 'Before Layer Change', type: 'textarea' },
      { key: 'layer_change_gcode', label: 'Layer Change', type: 'textarea' },
      { key: 'change_filament_gcode', label: 'Change Filament', type: 'textarea' },
      { key: 'printing_by_object_gcode', label: 'Print by Object', type: 'textarea' },
      { key: 'gcode_comments', label: 'Gcode Comments', type: 'toggle' },
      { key: 'disable_m73', label: 'Disable M73', type: 'toggle' },
    ],
  },
];
